### PR TITLE
[AITT] fix param type

### PR DESCRIPTION
**Pull request by jaeyun-jung**
Fix build error, AITT updated param type in subsribe callback.

Signed-off-by: Jaeyun <jy1210.jung@samsung.com>

### CODE REVIEW

**Review by yj99-shin — APPROVED** [review]
LGTM

**Comment by gichan-jang** [comment]
This patch was successfully built with the latest version of aitt.
However, the edgeAitt.connectLocal test fails.
I think the connection is terminated because the sleep time in test is too long, so AITT disconnects and reconnects.
So, please change sleep time of https://github.com/nnstreamer/nnstreamer-edge/blob/97f87cf98ecd7f85c920811805fdc39081db2ca5/tests/unittest_nnstreamer-edge-aitt.cc#L194 to usleep (10000);

**Review by myungjoo — APPROVED** [review]

**Comment by gichan-jang** [comment]
To fix test failure, see https://github.com/nnstreamer/nnstreamer-edge/pull/129

**Review by gichan-jang — APPROVED** [review]
LGTM, build test done on ubuntu local machine.

**Comment by jaeyun-jung** [comment]
Merge this PR, for AITT build.

**Pull request merged**
